CONFIG_XIP=n
CONFIG_NXP_IMXRT_BOOT_HEADER=n
CONFIG_BUILD_OUTPUT_BIN=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2S=y
CONFIG_DMA=y
CONFIG_DMA_MCUX_LPC=y
# Raise DMA TCD Queue size, as this is required by the I2S SAI driver
#CONFIG_DMA_TCD_QUEUE_SIZE=4
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_ADC=y
CONFIG_I2C_GPIO=y
CONFIG_LIS2DW12=y
CONFIG_TAS2563=y
# CONFIG_ADPD188=y
# CONFIG_ADPD188_TRIGGER=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LOG=y
#CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BACKEND_UART=y
#CONFIG_CODE_DATA_RELOCATION=y
# I2S logs
#CONFIG_I2S_LOG_LEVEL_DBG=y

# DMA logs  
#CONFIG_DMA_LOG_LEVEL_DBG=y

