CONFIG_XIP=n
CONFIG_NXP_IMXRT_BOOT_HEADER=n
CONFIG_BUILD_OUTPUT_BIN=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_I2S=y
CONFIG_DMA=y
CONFIG_DMA_MCUX_LPC=y
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_ADC=y
CONFIG_I2C_GPIO=y
#CONFIG_LIS2DW12=y
#CONFIG_TAS2563=y
#CONFIG_ADPD188=y
#CONFIG_ADPD188_TRIGGER=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LOG=y
#CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_LOG_BACKEND_UART=y
CONFIG_SDHC_LOG_LEVEL_DBG=y
CONFIG_LOG_MODE_IMMEDIATE=y
#CONFIG_CODE_DATA_RELOCATION=y
# I2S logs
#CONFIG_I2S_LOG_LEVEL_DBG=y

# DMA logs  
#CONFIG_DMA_LOG_LEVEL_DBG=y
#CONFIG_SPI=y
#CONFIG_LED_STRIP=y
#CONFIG_WS2812_STRIP=y
#CONFIG_WS2812_STRIP_SPI=y

CONFIG_INIT_SYS_PLL=y

# --- General Kernel Settings ---
CONFIG_HEAP_MEM_POOL_SIZE=16384
#CONFIG_MAIN_STACK_SIZE=4096

# --- SDIO / SDHC Configuration ---
#CONFIG_DISK_ACCESS=y
CONFIG_SDHC=y
CONFIG_IMX_USDHC=y
CONFIG_SDIO_STACK=y
CONFIG_SDHC_INIT_PRIORITY=80
CONFIG_IMX_USDHC_DMA_SUPPORT=y

#CONFIG_SDMMC_STACK=y
# --- Networking Stack (L3/L4) ---
# Since you selected WIFI_USE_NATIVE_NETWORKING, the RT685 runs the stack
CONFIG_NETWORKING=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_DHCPV4=y

# --- Wi-Fi Management ---
CONFIG_WIFI_INIT_PRIORITY=90
CONFIG_WIFI_ESP_HOSTED_SDIO=y
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_WIFI_NM=y
CONFIG_WIFI_LOG_LEVEL_INF=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# --- Protocol Buffers (Nanopb) ---
# The driver uses these to talk to the ESP32
CONFIG_NANOPB=y
CONFIG_NANOPB_ENABLE_MALLOC=y


