CONFIG_XIP=n
CONFIG_NXP_IMXRT_BOOT_HEADER=n
CONFIG_BUILD_OUTPUT_BIN=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y
CONFIG_ADC=y
CONFIG_I2C_GPIO=y
CONFIG_LIS2DW12=n
CONFIG_ADPD188=y
CONFIG_ADPD188_TRIGGER=n
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_UART=y
#CONFIG_CODE_DATA_RELOCATION=y

